flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    """
        Form for creating or updating a blog post.

        Fields:
            - title: Required. Title of the blog post.
            - content: Required. Body content of the post (textarea).
            - submit: Submit button labeled 'Post'.
    """
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flask_blog/main/routes.py
from flask import render_template, request, Blueprint
from flask_blog.models import Post


# create instance of Blueprint
main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def index():
    """
       Render the home page with paginated blog posts.

       - Retrieves the current page number from query parameters (defaults to 1).
       - Fetches posts ordered by most recent first.
       - Paginates the posts (5 per page).

       Returns:
           Response: Rendered home page with paginated posts.
   """
    # setting default page
    page = request.args.get('page', 1, type=int)
    # setting number of post per page
    # Note: this results in posts becoming a Pagination object
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)

@main.route("/about")
def about():
    """
        Render the About page.

        Returns:
            Response: Rendered static about page with title context.
    """
    return render_template('about.html', title="Flask Blog - About")

flask_blog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flask_blog import db
from flask_blog.models import Post
from flask_blog.posts.forms import PostForm


# create instance of Blueprint
posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    """
        Create a new blog post.

        - Displays a form to the logged-in user.
        - On valid submission, saves the post to the database.
        - Redirects to the homepage after creation.

        Returns:
            Response: Renders form or redirects after successful submission.
    """
    form = PostForm()
    if form.validate_on_submit():
        # creating post and adding post to db
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')  # flash: to send a one-time alert
        return redirect(url_for('main.index'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    """
        Display a single blog post.

        Args:
            post_id (int): ID of the post to display.

        Returns:
            Response: Renders the post detail template.
    """
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    """
        Update an existing blog post.

        - Only the author can update their own post.
        - Pre-fills the form with existing data.
        - Saves updated content to the database.

        Args:
            post_id (int): ID of the post to update.

        Returns:
            Response: Renders form or redirects after successful update.

        Raises:
            404 Resource Not Found: If post does not exist.
            403 Forbidden: If the user is not the author.
    """
    # get post if exist else throw 404 error
    post = Post.query.get_or_404(post_id)
    # check authorized user for post else throw 403 error
    if post.author != current_user:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        # update post and commit to db
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id)) # redirect required due to post-get-redirect pattern
    elif request.method == 'GET':
        # populate form with existing post title and content
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    """
       Delete an existing blog post.

       - Only the post's author is authorized to delete it.
       - Post is removed from the database.

       Args:
           post_id (int): ID of the post to delete.

       Returns:
           Response: Redirects to the homepage after deletion.

       Raises:
           404 Resource Not Found: If post does not exist.
           403 Forbidden: If the user is not the author.
   """
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.index'))

flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flask_blog.users.utils import save_picture, send_reset_email


# create instance of Blueprint
users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    """
        Handle user registration.

        - Redirects authenticated users to the main index page.
        - Displays a registration form for new users.
        - Validates form submission and creates a new user account with a hashed password.
        - Commits the user to the database and flashes a success message upon successful registration.
        - Redirects the user to the login page after registration.

        Returns:
            Response: Rendered registration template on GET or failed POST.
                      Redirect to login page on successful registration.
    """
    # check existing logged in user
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        # get hashed password
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # creating user
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        # adding user to db
        db.session.add(user)
        db.session.commit()
        # show feedback
        flash(f'Account created for {form.username.data.title()}! You are able to login with your new account!', 'success') # flash: to send a one-time alert
        return redirect(url_for('users.login'))
    return render_template('register.html', title="Flask Blog - Register", form=form)


@users.route("/login", methods=['GET', 'POST']) # name of route
def login(): # name of function
    """
        Handle user login.

        - Redirects authenticated users to the home page.
        - Processes login form submission.
        - Authenticates user using email and password.
        - Redirects to the originally requested page if specified (`next` parameter).
        - Flashes success or error messages.

        Returns:
            Response: Renders login page or redirects to the appropriate page after login.
    """
    # check existing logged in user
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        # check if user exists in database
        user = User.query.filter_by(email=form.email.data).first()
        # check password matches in database
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            # add next_page routing to where page user was trying to access but prompted for login
            # sample url: http://localhost:5001/login?next=%2Faccount
            next_page = request.args.get('next')
            flash(f'Logged in for account {form.email.data}', 'success')  # flash: to send a one-time alert
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Invalid login credentials', 'danger')  # flash: to send a one-time alert
    return render_template('login.html', title="Flask Blog - Login", form=form)


@users.route("/logout")
def logout():
    """
        Logs out the current user and redirects to the main index page.

        Returns:
            Response: Redirect to home page.
    """
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    """
        Display and update the current user's account information.

        - Allows users to update their username, email, and profile picture.
        - Pre-populates the form with current values on GET request.
        - Commits changes on POST and redirects to avoid form resubmission.

        Returns:
            Response: Renders the account page or redirects after successful update.
    """
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        # update username and email via current_user and commiting to db
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')  # flash: to send a one-time alert
        return redirect(url_for('users.account')) # redirect required due to post-get-redirect pattern
    elif request.method == 'GET': # populate fields with current_user data
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    """
       Display blog posts by a specific user.

       Args:
           username (str): Username of the user whose posts are being viewed.

       Returns:
           Response: Renders a paginated list of blog posts by the user.
   """
    page = request.args.get('page', 1, type=int)
    # getting user from username
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query\
            .filter_by(author=user)\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    """
        Handle password reset request.

        - Prevents logged-in users from accessing.
        - Sends a password reset email if the provided email is registered.

        Returns:
            Response: Renders password reset request page or redirects after sending email.
    """
    # check existing logged in user
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',title="Request Reset Password", form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    """
        Handle password reset using a secure token.

        - Verifies the token and identifies the user.
        - Allows user to set a new password if the token is valid.
        - Flashes feedback messages on success or failure.

        Args:
            token (str): Secure token used to verify password reset request.

        Returns:
            Response: Renders reset password form or redirects on failure/success.
    """
    # check existing logged in user
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired token.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        # get hashed password
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # set new password
        user.password = hashed_password
        db.session.commit()
        # show feedback
        flash(f'Password successfully reset for {user.email}! You are able to login with your new password!', 'success') # flash: to send a one-time alert
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title="Reset Password", form=form)

flask_blog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flask_blog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username.title() }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <form method="POST" action="", enctype="multipart/form-data"> <!-- enctype ie.'encoding type' required for FileField to prevent errors -->
            {{ form.hidden_tag() }}  <!-- adds csrf token -->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    <!-- handling error and feedback on invalid field input -->
                    {% if form.username.errors %}
                      {{ form.username(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                    {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    <!-- handling error and feedback on invalid field input -->
                    {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                    {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}  <!-- adds csrf token -->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    <!-- handling error and feedback on invalid field input -->
                    {% if form.title.errors %}
                      {{ form.title(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                    {% else %}
                      {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    <!-- handling error and feedback on invalid field input -->
                    {% if form.content.errors %}
                      {{ form.content(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                    {% else %}
                      {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_blog/templates/home.html
{% extends "layout.html" %}
{% block content %}
  {% if current_user.is_authenticated %}
    <h4 style="color: #2aacb6">Welcome, {{ current_user.username.title() }}</h4>
  {% endif %}
<!-- use posts.items to retrieve post from Pagination object -->
  {% for post in posts.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username.title() }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%B %d, %Y') }}</small>
        </div>
        <h2 class="article-title-h2"><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
  {% endfor %}

  <div class="d-flex justify-content-center flex-wrap">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} <!-- adding limits to displayed pagination -->
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4 mx-1" style="border-radius: 10px" href="{{ url_for('main.index', page=page_num)}}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4 mx-1" style="border-radius: 10px" href="{{ url_for('main.index', page=page_num)}}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>

{% endblock content %}

flask_blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

                                                <!-- url_for('directory', filename='filename')   -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-teal fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('main.index') }}">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.index') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          <!-- get_flashed_message: function that will get the flashed messages -->
          <!-- with_categories: grabs category that is passed into flashed messages -->
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category,message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flask_blog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}  <!-- adds csrf token -->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    <!-- handling error and feedback on invalid field input -->
                    {% if form.email.errors %}
                      {{ form.email(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                    {% else %}
                      {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    <!-- handling error and feedback on invalid field input -->
                    {% if form.password.errors %}
                      {{ form.password(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                    {% else %}
                      {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Do not have an account?
            <a class="ml-2" href="{{ url_for('users.register') }}">Sign In</a> <!-- note: in url_for, 'register' is name of function not name of route -->
        </small>
    </div>
{% endblock content %}

flask_blog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username.title() }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%B %d, %Y') }}</small>
      </div>
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <h2 class="article-title article-title-h2">{{ post.title }}</h2>
        </div>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-danger btn-sm mb-1 ml-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
<!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST" style="display: inline;">
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

flask_blog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
<h2 class="mb-3">Posts by {{ user.username.title() }} ({{ posts.total }} posts)</h2>
<!-- use posts.items to retrieve post from Pagination object -->
  {% for post in posts.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username.title() }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%B %d, %Y') }}</small>
        </div>
        <h2 class="article-title-h2"><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
  {% endfor %}

  <div class="d-flex justify-content-center flex-wrap">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %} <!-- adding limits to displayed pagination -->
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4 mx-1" style="border-radius: 10px" href="{{ url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4 mx-1" style="border-radius: 10px" href="{{ url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>

{% endblock content %}